### ISSUE TITLE
Switch in `murl_render` is missing case for `MU_ICON_MAX`

### ISSUE THREAD

**Issue by ashn-dot-dev** [marionauta/microui-raylib#1]
Should be handed by this switch:

https://github.com/marionauta/microui-raylib/blob/f996e01ce8d7ddaa3de97fadc1e066c6202833b2/src/murl.c#L132

**Comment by ashn-dot-dev** [comment]
Upon further inspection, it looks like `MU_ICON_MAX` is intended to be used for declaring fixed-sized arrays, and I was likely using the API wrong. So this is in fact, not actually a bug.

**Comment by marionauta** [comment]
@ashn-dot-dev Thanks for checking! While `MU_ICON_MAX` is not an actual icon, I know that one is still missing: a "grab" on the bottom right corner of the windows, used to resize them — you can see it on the browser demo of microui. Development is a bit paused in this repo at the moment, as I haven't had time, but that's the next thing I want to find.
